name: Trigger auto deployment for spring-ai-movie-generator

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/spring-ai-movie-generator-AutoDeployTrigger-e0bf8249-4e1c-4b3a-8893-eb56551d8450.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SPRINGAIMOVIEGENERATOR_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SPRINGAIMOVIEGENERATOR_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SPRINGAIMOVIEGENERATOR_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.SPRINGAIMOVIEGENERATOR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SPRINGAIMOVIEGENERATOR_REGISTRY_PASSWORD }}
          containerAppName: spring-ai-movie-generator
          resourceGroup: spring-ai-movie-generator
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


